PROJECT_NAME: medpoint-be
PROJECT_ID: blobjyapgzwdqivpbdfq
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_d3d22b50b883d3aa2fbe52e324518ee514c0cbae
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb2JqeWFwZ3p3ZHFpdnBiZGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0Mzg0MjAsImV4cCI6MjA1MDAxNDQyMH0.-zJT9WeECDFzbhtyUUXEWHFh_LzX7fVEM5vMjB1lyEI
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsb2JqeWFwZ3p3ZHFpdnBiZGZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNDQzODQyMCwiZXhwIjoyMDUwMDE0NDIwfQ.DoSNhxsyjCELE29dGA9oF0wvlOMZ9xx2Ozqg_rC8d9s

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: /v1/projects
SUPABASE_PUBLIC_URL: https://blobjyapgzwdqivpbdfq.supabase.co

SERVER_HOST: 0.0.0.0
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR:
TRACE_COLLECTOR_ENDPOINT:

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
