PROJECT_NAME: medpoint-be
PROJECT_ID:
DEPLOYMENT_TARGET: self_hosted

ACCESS_TOKEN:
ANON_KEY: your_supabase_anon_key
SERVICE_KEY: your_supabase_service_key

SUPABASE_API_URL: http://localhost:54323
SUPABASE_API_BASE_PATH: /api/pg-meta/default
SUPABASE_PUBLIC_URL: your_supabase_public_url

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR:
TRACE_COLLECTOR_ENDPOINT:

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
